# Generated by Django 5.1 on 2024-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='logout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
