# Generated by Django 5.1 on 2024-08-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useractivity_login_alter_useractivity_logout'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
